MKINCL?=/bbsrc/mkincludes/
include $(MKINCL)machdep.newlink
include /bbsrc/tools/data/libmacros.mk

USER_FFLAGS=$(FPIC)

USER_CFLAGS=$(WALL) $(CPIC) -I.

S_BREGUISVC_CPPFLAGS ?= -I.

USER_CPPFLAGS  = -I.
USER_CPPFLAGS += $(S_BREGUISVC_CPPFLAGS)

IS_BDE=yes
IS_PTHREAD=yes
IS_EXCEPTION=yes

# Comment the line below to disable dependency builds
IS_DEPENDS_NATIVE=yes

# Remove "yes" in the macro definition below to disable inlining
INLINING=yes

ANAME=libs_breguisvc.a
SNAME=libs_breguisvc.so

###
### DO NOT CHANGE THE DEFINITION OF THE 'MSGOBJS' MACRO
###
MSGOBJS=\
s_breguisvc_messages.o \

###
### Add additional components to the 'AOBJS' macro
###
AOBJS=\
$(MSGOBJS) \
s_breguisvc_buildopts.o \
s_breguisvc_manifest.o \
s_breguisvc_entry.o \
s_breguisvc_requestcontext.o \
s_breguisvc_requestrouter.o \
s_breguisvc_requestprocessor.o \
s_breguisvc_version.o \
s_breguisvc_versiontag.o \

SOBJS=$(AOBJS)

-include local.mk

include $(MKINCL)/$(if $(BAS_LINK_STATIC),linklib,linkso).newlink

# $Id$ $CSID$ $CCId$
# GENERATED BY BLP_BAS_CODEGEN_3.6.22 Mon Jun  3 14:37:57 2013
