// s_breguisvc_manifest.cpp      *GENERATED FILE - DO NOT EDIT*       -*-C++-*-

#include <bdes_ident.h>
BDES_IDENT_RCSID(s_breguisvc_manifest_cpp,"$Id$ $CSID$")

#include <s_breguisvc_manifest.h>
#include <s_breguisvc_versiontag.h>

namespace BloombergLP {
namespace s_breguisvc {

                               // --------------
                               // class Manifest
                               // --------------

// CLASS DATA

const int   Manifest::d_majorVersion      = S_BREGUISVC_VERSION_MAJOR;
const int   Manifest::d_minorVersion      = S_BREGUISVC_VERSION_MINOR;
const char *Manifest::d_schemaNamespace_p =
           "urn:x-bloomberg-com:BAS.services.breguisvc";
const char *Manifest::d_requestElement_p  = "request";
const char *Manifest::d_responseElement_p = "response";

}  // close namespace s_breguisvc
}  // close namespace BloombergLP

// GENERATED BY BLP_BAS_CODEGEN_3.8.4 Wed Apr 22 09:48:00 2015
// USING bas_codegen.pl -m all --bidirectional breguisvc.xsd
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., 2015
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------- END-OF-FILE --------------------------------
