// s_breguisvc_version.h   -*-C++-*-
#ifndef INCLUDED_S_BREGUISVC_VERSION
#define INCLUDED_S_BREGUISVC_VERSION

#ifndef INCLUDED_BDES_IDENT
#include <bdes_ident.h>
#endif
BDES_IDENT_RCSID(s_breguisvc_version_h,"$Id$ $CSID$ $CCId$")
BDES_IDENT_PRAGMA_ONCE

//@PURPOSE: Provide source control management (versioning) information.
//
//@CLASSES:
//  s_breguisvc::Version: namespace for RCS and SCCS versioning information
//
//@AUTHOR: Marcos Lara Reinhold (mlarareinhol@bloomberg.net)
//
//@DESCRIPTION: This component provides source control management (versioning)
// information for the 'BREGUISVC' service.  In particular, this component
// embeds RCS-style and SCCS-style version strings in binary executable files
// that use one or more components from the 's_breguisvc' package.  This version
// information may be extracted from binary files using common UNIX utilities
// (e.g., 'ident' and 'what').  In addition, the 'version' 'static' member
// function in the 'Version' 'struct' can be used to query version
// information for the 's_breguisvc' package group at runtime.  The following
// usage examples illustrate these two basic capabilities.
//
///Usage
///-----
// A program can display the version of BREGUISVC service that was used to
// build it by printing the version string returned by
// 's_breguisvc::Version::version()' to 'stdout' as follows:
//..
//  std::printf("BREGUISVC version: \%s\n", s_breguisvc::Version::version());
//..

namespace BloombergLP {
namespace s_breguisvc {

                               // ==============
                               // struct Version
                               // ==============

struct Version {
    static const char *d_ident;
    static const char *d_what;

    static const char *d_version;
    static const char *d_dependencies;
    static const char *d_buildInfo;
    static const char *d_timestamp;
    static const char *d_sourceControlInfo;

    static const char *version();
};

inline
const char *Version::version()
{
    return d_version;
}

static volatile const char s_breguisvc_version_assertion =
        Version::d_version != 0;

}  // close namespace s_breguisvc
}  // close namespace BloombergLP
#endif

// GENERATED BY BLP_BAS_CODEGEN_3.5.3 Tue Sep 14 13:44:26 2010
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., 2010
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------- END-OF-FILE --------------------------------
