// s_breguisvc_buildopts.cpp      *GENERATED FILE - DO NOT EDIT*      -*-C++-*-

#include <bdes_ident.h>
BDES_IDENT_RCSID(s_breguisvc_buildopts_cpp,"$Id$ $CSID$")

#include <s_breguisvc_buildopts.h>

// GENERATED BY BLP_BAS_CODEGEN_3.8.4 Wed Apr 22 09:48:00 2015
// USING bas_codegen.pl -m all --bidirectional breguisvc.xsd
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., 2015
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------ END-OF-FILE ---------------------------------
