// s_breguisvc_versiontag.cpp   -*-C++-*-

#include <bdes_ident.h>
BDES_IDENT_RCSID(s_breguisvc_versiontag_cpp,"$Id$ $CSID$ $CCId$")

#include <s_breguisvc_versiontag.h>

// GENERATED BY BLP_BAS_CODEGEN_3.5.3 Tue Sep 14 13:44:26 2010
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., 2010
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------- END-OF-FILE --------------------------------
