// s_breguisvc_buildopts.h       *GENERATED FILE - DO NOT EDIT*       -*-C++-*-
#ifndef INCLUDED_S_BREGUISVC_BUILDOPTS
#define INCLUDED_S_BREGUISVC_BUILDOPTS

#ifndef INCLUDED_BDES_IDENT
#include <bdes_ident.h>
#endif
BDES_IDENT_RCSID(s_breguisvc_buildopts_h,"$Id$ $CSID$")
BDES_IDENT_PRAGMA_ONCE

//@PURPOSE: Provide a namespace for core framework class type aliases
//
//@CLASSES:
// s_breguisvc::BuildOpts: namespace for core framework class type aliases
//
//@AUTHOR: Sarah ZHANG (yzhang744@bloomberg.net)
//
//@DESCRIPTION: This component provides a namespace for type aliases for core
// framework classes selected according to various compiler macros.  These
// macros dictate how a BAS service should be deployed:
//..
//  BAS_NOBBENV - non-Bloomberg environment aware service
//
//  BAS_AGGREGATE_ROUTER - deploy as an in-process service
//..
// By default, services are aware of the Bloomberg environment, meaning that
// they can communicate via FastSend, and can attach to common areas and call
// various legacy functions such as comdb[2] accessors.  Defining the
// BAS_NOBBENV compiler flag results in a service which can do none of these
// things, and communicates only via TCP/IP.
//
// Baslets, or in-process services, are optimized for size by translating
// driectly between generated types and 'bcem_Aggregate'.  Hence, baslets do
// not support any wire-format encodings (XML, BER, BDEX, etc).
//
//@USAGE EXAMPLES
// The following examples illustrate how to choose build options by setting
// compiler flags, assuming the bas_codegen.pl generated plink makefile.
//
// The following command builds a non-Bloomberg environment aware service
//..
//   BAS_NOBBENV=yes plink service.mk
//..
//
// The following command builds an in-process service (library)
//..
//   BAS_AGGREGATE_ROUTER=yes plink libs_service.mk
//..

#ifndef INCLUDED_S_BREGUISVC_VERSION
#include <s_breguisvc_version.h>
#endif

#ifdef BAS_AGGREGATE_ROUTER
// Core BAS Framework (Baslet)
#ifndef INCLUDED_BASSVC_AGGREGATEREQUESTCONTEXT
#include <bassvc_aggregaterequestcontext.h>
#endif
#ifndef INCLUDED_BASSVC_AGGREGATEREQUESTROUTER
#include <bassvc_aggregaterequestrouter.h>
#endif
#ifndef INCLUDED_BASSVC_AGGREGATEREQUESTROUTERIMP
#include <bassvc_aggregaterequestrouterimp.h>
#endif
#ifndef INCLUDED_BCEM_AGGREGATE
#include <bcem_aggregate.h>
#endif
#else
// Core BAS Framework (Offline)
#ifndef INCLUDED_BASSVC_REQUESTCONTEXT
#include <bassvc_requestcontext.h>
#endif
#ifndef INCLUDED_BASSVC_REQUESTROUTER
#include <bassvc_requestrouter.h>
#endif
#ifndef INCLUDED_BASSVC_REQUESTROUTERIMP
#include <bassvc_requestrouterimp.h>
#endif
#ifndef INCLUDED_BCEMA_BLOB
#include <bcema_blob.h>
#endif
#endif

namespace BloombergLP {

namespace s_breguisvc { class Request; }
namespace s_breguisvc {

                              // ================
                              // struct BuildOpts
                              // ================

struct BuildOpts {
    // This class provides a namespace for type aliases selected according to
    // various compiler macros.

#ifdef BAS_AGGREGATE_ROUTER
    // Core BAS Framework (Baslet)
    typedef bassvc::AggregateRequestContext            RequestContext;
    typedef bassvc::AggregateRequestRouter             RequestRouter;
    typedef bassvc::AggregateRequestRouterImp<Request> RequestRouterImp;
    typedef bcem_Aggregate                             RawRequest;
#else
    // Core BAS Framework (Offline)
    typedef bassvc::RequestContext                     RequestContext;
    typedef bassvc::RequestRouter                      RequestRouter;
    typedef bassvc::RequestRouterImp<Request>          RequestRouterImp;
    typedef bcema_Blob                                 RawRequest;
#endif
};

}  // close namespace s_breguisvc
}  // close namespace BloombergLP
#endif

// GENERATED BY BLP_BAS_CODEGEN_3.8.4 Wed Apr 22 09:48:00 2015
// USING bas_codegen.pl -m all --bidirectional breguisvc.xsd
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., 2015
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------ END-OF-FILE ---------------------------------
