// s_breguisvc_version.cpp   -*-C++-*-

#include <bdes_ident.h>
BDES_IDENT_RCSID(s_breguisvc_version_cpp,"$Id$ $CSID$ $CCId$")

#include <s_breguisvc_version.h>
#include <s_breguisvc_versiontag.h>

namespace BloombergLP {
namespace s_breguisvc {

                               // --------------
                               // struct Version
                               // --------------

// Increment the version in the following way:
// - increment VERSION_PATCH for each binary compatible bug fix
// - increment VERSION_MINOR for each binary compatible interface extension
// - increment VERSION_MAJOR for each source incompatible change

#define STRINGIFY2(a) #a
#define STRINGIFY(a)  STRINGIFY2(a)

#define S_BREGUISVC_VERSION_PATCH  0
#define S_BREGUISVC_VERSION_STRING "BLP_BAS_LIB_S_BREGUISVC_" \
        STRINGIFY(S_BREGUISVC_VERSION_MAJOR) \
    "." STRINGIFY(S_BREGUISVC_VERSION_MINOR) \
    "." STRINGIFY(S_BREGUISVC_VERSION_PATCH)

const char *Version::d_ident = "$Id: "S_BREGUISVC_VERSION_STRING" $";
const char *Version::d_what  = "@(#)"S_BREGUISVC_VERSION_STRING;

const char *Version::d_version           = S_BREGUISVC_VERSION_STRING;
const char *Version::d_dependencies      = "";
const char *Version::d_buildInfo         = "";
const char *Version::d_timestamp         = "";
const char *Version::d_sourceControlInfo = "";

}  // close namespace s_breguisvc
}  // close namespace BloombergLP

// GENERATED BY BLP_BAS_CODEGEN_3.5.3 Tue Sep 14 13:44:26 2010
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., 2010
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------- END-OF-FILE --------------------------------
