// s_breguisvc_manifest.h       *GENERATED FILE - DO NOT EDIT*        -*-C++-*-
#ifndef INCLUDED_S_BREGUISVC_MANIFEST
#define INCLUDED_S_BREGUISVC_MANIFEST

#ifndef INCLUDED_BDES_IDENT
#include <bdes_ident.h>
#endif
BDES_IDENT_RCSID(s_breguisvc_manifest_h,"$Id$ $CSID$")
BDES_IDENT_PRAGMA_ONCE

//@PURPOSE: Provide metadata for the BREGUISVC service.
//
//@CLASSES:
// s_breguisvc::Manifest
//
//@AUTHOR: none
//
//@DESCRIPTION: This component provides metadata for the BREGUISVC service
// that can be loaded into an object of type 'bassvc::ServiceManifest'.

#ifndef INCLUDED_S_BREGUISVC_VERSION
#include <s_breguisvc_version.h>
#endif

namespace BloombergLP {
namespace s_breguisvc {

                               // ==============
                               // class Manifest
                               // ==============

class Manifest {
    // This class encapsulates metadata for the BREGUISVC service.

    // CLASS DATA
    static const int   d_majorVersion;      // service major version number
    static const int   d_minorVersion;      // service minor version number
    static const char *d_schemaNamespace_p; // service schema targetNamespace
    static const char *d_requestElement_p;  // top-level request element name
    static const char *d_responseElement_p; // top-level response element name

  public:
    // CLASS METHODS
    static int majorVersion();
        // Return the "major version" attribute of this manifest.

    static int minorVersion();
        // Return the "minor version" attribute of this manifest.

    static const char *schemaNamespace();
        // Return the "schema namespace" attribute of this manifest.

    static const char *requestElement();
        // Return the "requestlement" attribute of this manifest.

    static const char *responseElement();
        // Return the "response element" attribute of this manifest.
};

// ============================================================================
//                          INLINE FUNCTION DEFINITIONS
// ============================================================================

// CLASS METHODS
inline
int Manifest::majorVersion()
{
    return d_majorVersion;
}

inline
int Manifest::minorVersion()
{
    return d_minorVersion;
}

inline
const char *Manifest::schemaNamespace()
{
    return d_schemaNamespace_p;
}

inline
const char *Manifest::requestElement()
{
    return d_requestElement_p;
}

inline
const char *Manifest::responseElement()
{
    return d_responseElement_p;
}

}  // close namespace s_breguisvc
}  // close namespace BloombergLP
#endif

// GENERATED BY BLP_BAS_CODEGEN_3.8.4 Wed Apr 22 09:48:00 2015
// USING bas_codegen.pl -m all --bidirectional breguisvc.xsd
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., 2015
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------- END-OF-FILE --------------------------------
