// s_breguisvc_messages.h       *GENERATED FILE - DO NOT EDIT*        -*-C++-*-
#ifndef INCLUDED_S_BREGUISVC_MESSAGES
#define INCLUDED_S_BREGUISVC_MESSAGES

#ifndef INCLUDED_BDES_IDENT
#include <bdes_ident.h>
#endif
BDES_IDENT_RCSID(s_breguisvc_messages_h,"$Id$ $CSID$")
BDES_IDENT_PRAGMA_ONCE

//@PURPOSE: Provide types and codecs used by S_BREGUISVC messages

#ifndef INCLUDED_S_BREGUISVC_SCHEMA
#include <s_breguisvc_schema.h>
#endif

#ifndef INCLUDED_S_BREGUISVC_SCHEMAUTIL
#include <s_breguisvc_schemautil.h>
#endif

#endif

// GENERATED BY BLP_BAS_CODEGEN_3.8.4 Fri Apr 24 17:04:51 2015
// USING bas_codegen.pl -m msg --bidirectional breguisvc.xsd
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., 2015
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------- END-OF-FILE --------------------------------
